import json
import time
import sys

def create_test_report(model, history, test_results, config, save_path="test_report.json"):
    """
    Creates a JSON report of test results and model configuration.
    
    Parameters:
        model (keras.Model): The trained model.
        history (dict): Training history object containing metrics data.
        test_results (dict): Dictionary containing test loss and accuracy.
        config (dict): Configuration used for the model, including loss and optimizer.
        save_path (str): Path where the report JSON file will be saved.

    Returns:
        dict: A dictionary containing the full report.
    """
    report = {
        "Model Details": {
            "Architecture": str(model.summary()),
            "Parameters": model.count_params(),
            "Loss Function": config['loss_function'],
            "Optimizer": config['optimizer']
        },
        "Test Results": {
            "Test Loss": test_results['loss'],
            "Test Accuracy": test_results['accuracy'],
        },
        "System Environment": {
            "Python Version": sys.version,
        },
        "Metadata": {
            "Report Generated": time.strftime("%Y-%m-%d %H:%M:%S"),
            "Duration": f"{test_results['duration']} seconds",
            "Generated By": "[C.A.S](CrowDar Automation System)"
        }
    }

    with open(save_path, 'w') as file:
        json.dump(report, file, indent=4)

    return report
