import json
import time
import numpy as np
import sys

def create_test_report(model, history, test_results, config, save_path="test_report.json"):
    report = {
        "Model Details": {
            "Architecture": str(model),
            "Parameters": model.count_params(),
            "Loss Function": config['loss_function'],
            "Optimizer": config['optimizer']
        },
        "Test Results": {
            "Test Loss": test_results['loss'],
            "Test Accuracy": test_results['accuracy'],
        },
        "System Environment": {
            "Python Version": sys.version,
        },
        "Metadata": {
            "Report Generated": time.strftime("%Y-%m-%d %H:%M:%S"),
            "Duration": f"{test_results['duration']} seconds",
            "Generated By": "[C.A.S](CrowDar Automation System)"
        }
    }

    with open(save_path, 'w') as f:
        json.dump(report, f, indent=4)

    return report